2024-10-15 10:33:58,103 INFO    Thread-1467 (_run_job):30356 [wandb_setup.py:_flush():76] Current SDK version is 0.16.0
2024-10-15 10:33:58,103 INFO    Thread-1467 (_run_job):30356 [wandb_setup.py:_flush():76] Configure stats pid to 30356
2024-10-15 10:33:58,103 INFO    Thread-1467 (_run_job):30356 [wandb_setup.py:_flush():76] Loading settings from C:\Users\Estudiantes\.config\wandb\settings
2024-10-15 10:33:58,103 INFO    Thread-1467 (_run_job):30356 [wandb_setup.py:_flush():76] Loading settings from C:\Users\Estudiantes\Documents\copy\Mamitas-Unal\wandb\settings
2024-10-15 10:33:58,103 INFO    Thread-1467 (_run_job):30356 [wandb_setup.py:_flush():76] Loading settings from environment variables: {'project': 'weak_supervised_learning', 'entity': 'mamitas', 'api_key': '***REDACTED***', 'root_dir': 'C:\\Users\\Estudiantes\\Documents\\copy\\Mamitas-Unal', 'run_id': 'vzg97yv3', 'sweep_param_path': 'C:\\Users\\Estudiantes\\Documents\\copy\\Mamitas-Unal\\wandb\\sweep-grzo9tov\\config-vzg97yv3.yaml', 'sweep_id': 'grzo9tov'}
2024-10-15 10:33:58,103 INFO    Thread-1467 (_run_job):30356 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2024-10-15 10:33:58,103 INFO    Thread-1467 (_run_job):30356 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program_relpath': 'code\\trains.py', 'program_abspath': 'c:\\Users\\Estudiantes\\Documents\\copy\\Mamitas-Unal\\code\\trains.py', 'program': 'c:\\Users\\Estudiantes\\Documents\\copy\\Mamitas-Unal\\code\\trains.py'}
2024-10-15 10:33:58,103 INFO    Thread-1467 (_run_job):30356 [wandb_init.py:_log_setup():524] Logging user logs to C:\Users\Estudiantes\Documents\copy\Mamitas-Unal\wandb\run-20241015_103358-vzg97yv3\logs\debug.log
2024-10-15 10:33:58,103 INFO    Thread-1467 (_run_job):30356 [wandb_init.py:_log_setup():525] Logging internal logs to C:\Users\Estudiantes\Documents\copy\Mamitas-Unal\wandb\run-20241015_103358-vzg97yv3\logs\debug-internal.log
2024-10-15 10:33:58,103 INFO    Thread-1467 (_run_job):30356 [wandb_init.py:init():564] calling init triggers
2024-10-15 10:33:58,103 INFO    Thread-1467 (_run_job):30356 [wandb_init.py:init():571] wandb.init called with sweep_config: {'dataset': 'infrared_thermal_feet', 'model': 'r_b_s'}
config: {}
2024-10-15 10:33:58,103 INFO    Thread-1467 (_run_job):30356 [wandb_init.py:init():614] starting backend
2024-10-15 10:33:58,103 INFO    Thread-1467 (_run_job):30356 [wandb_init.py:init():618] setting up manager
2024-10-15 10:33:58,118 INFO    Thread-1467 (_run_job):30356 [backend.py:_multiprocessing_setup():105] multiprocessing start_methods=spawn, using: spawn
2024-10-15 10:33:58,122 INFO    Thread-1467 (_run_job):30356 [wandb_init.py:init():624] backend started and connected
2024-10-15 10:33:58,135 INFO    Thread-1467 (_run_job):30356 [wandb_run.py:_config_callback():1342] config_cb None None {'dataset': 'infrared_thermal_feet', 'model': 'r_b_s'}
2024-10-15 10:33:58,135 INFO    Thread-1467 (_run_job):30356 [wandb_init.py:init():716] updated telemetry
2024-10-15 10:33:58,182 INFO    Thread-1467 (_run_job):30356 [wandb_init.py:init():749] communicating run to backend with 90.0 second timeout
2024-10-15 10:33:58,530 INFO    Thread-1467 (_run_job):30356 [wandb_run.py:_on_init():2254] communicating current version
2024-10-15 10:33:58,624 INFO    Thread-1467 (_run_job):30356 [wandb_run.py:_on_init():2263] got version response upgrade_message: "wandb version 0.18.3 is available!  To upgrade, please run:\n $ pip install wandb --upgrade"

2024-10-15 10:33:58,624 INFO    Thread-1467 (_run_job):30356 [wandb_init.py:init():800] starting run threads in backend
2024-10-15 10:33:59,748 INFO    Thread-1467 (_run_job):30356 [wandb_run.py:_console_start():2233] atexit reg
2024-10-15 10:33:59,748 INFO    Thread-1467 (_run_job):30356 [wandb_run.py:_redirect():2088] redirect: wrap_raw
2024-10-15 10:33:59,748 INFO    Thread-1467 (_run_job):30356 [wandb_run.py:_redirect():2153] Wrapping output streams.
2024-10-15 10:33:59,748 INFO    Thread-1467 (_run_job):30356 [wandb_run.py:_redirect():2178] Redirects installed.
2024-10-15 10:33:59,748 INFO    Thread-1467 (_run_job):30356 [wandb_init.py:init():841] run started, returning control to user process
2024-10-15 10:34:20,306 ERROR   Thread-1467 (_run_job):30356 [keras.py:_save_model():1012] `save_model()` using h5 format requires h5py. Could not import h5py.
Traceback (most recent call last):
  File "C:\Users\Estudiantes\miniconda3\envs\mamitasHugo\lib\site-packages\wandb\integration\keras\keras.py", line 1004, in _save_model
    self.model.save(self.filepath, overwrite=True)
  File "C:\Users\Estudiantes\miniconda3\envs\mamitasHugo\lib\site-packages\keras\utils\traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "C:\Users\Estudiantes\miniconda3\envs\mamitasHugo\lib\site-packages\keras\saving\hdf5_format.py", line 80, in save_model_to_hdf5
    raise ImportError(
ImportError: `save_model()` using h5 format requires h5py. Could not import h5py.
2024-10-15 10:35:40,807 ERROR   Thread-1467 (_run_job):30356 [keras.py:_save_model():1012] `save_model()` using h5 format requires h5py. Could not import h5py.
Traceback (most recent call last):
  File "C:\Users\Estudiantes\miniconda3\envs\mamitasHugo\lib\site-packages\wandb\integration\keras\keras.py", line 1004, in _save_model
    self.model.save(self.filepath, overwrite=True)
  File "C:\Users\Estudiantes\miniconda3\envs\mamitasHugo\lib\site-packages\keras\utils\traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "C:\Users\Estudiantes\miniconda3\envs\mamitasHugo\lib\site-packages\keras\saving\hdf5_format.py", line 80, in save_model_to_hdf5
    raise ImportError(
ImportError: `save_model()` using h5 format requires h5py. Could not import h5py.
2024-10-15 10:36:06,632 ERROR   Thread-1467 (_run_job):30356 [keras.py:_save_model():1012] `save_model()` using h5 format requires h5py. Could not import h5py.
Traceback (most recent call last):
  File "C:\Users\Estudiantes\miniconda3\envs\mamitasHugo\lib\site-packages\wandb\integration\keras\keras.py", line 1004, in _save_model
    self.model.save(self.filepath, overwrite=True)
  File "C:\Users\Estudiantes\miniconda3\envs\mamitasHugo\lib\site-packages\keras\utils\traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "C:\Users\Estudiantes\miniconda3\envs\mamitasHugo\lib\site-packages\keras\saving\hdf5_format.py", line 80, in save_model_to_hdf5
    raise ImportError(
ImportError: `save_model()` using h5 format requires h5py. Could not import h5py.
2024-10-15 10:36:20,264 ERROR   Thread-1467 (_run_job):30356 [keras.py:_save_model():1012] `save_model()` using h5 format requires h5py. Could not import h5py.
Traceback (most recent call last):
  File "C:\Users\Estudiantes\miniconda3\envs\mamitasHugo\lib\site-packages\wandb\integration\keras\keras.py", line 1004, in _save_model
    self.model.save(self.filepath, overwrite=True)
  File "C:\Users\Estudiantes\miniconda3\envs\mamitasHugo\lib\site-packages\keras\utils\traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "C:\Users\Estudiantes\miniconda3\envs\mamitasHugo\lib\site-packages\keras\saving\hdf5_format.py", line 80, in save_model_to_hdf5
    raise ImportError(
ImportError: `save_model()` using h5 format requires h5py. Could not import h5py.
2024-10-15 10:36:45,673 ERROR   Thread-1467 (_run_job):30356 [keras.py:_save_model():1012] `save_model()` using h5 format requires h5py. Could not import h5py.
Traceback (most recent call last):
  File "C:\Users\Estudiantes\miniconda3\envs\mamitasHugo\lib\site-packages\wandb\integration\keras\keras.py", line 1004, in _save_model
    self.model.save(self.filepath, overwrite=True)
  File "C:\Users\Estudiantes\miniconda3\envs\mamitasHugo\lib\site-packages\keras\utils\traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "C:\Users\Estudiantes\miniconda3\envs\mamitasHugo\lib\site-packages\keras\saving\hdf5_format.py", line 80, in save_model_to_hdf5
    raise ImportError(
ImportError: `save_model()` using h5 format requires h5py. Could not import h5py.
2024-10-15 10:37:09,641 ERROR   Thread-1467 (_run_job):30356 [keras.py:_save_model():1012] `save_model()` using h5 format requires h5py. Could not import h5py.
Traceback (most recent call last):
  File "C:\Users\Estudiantes\miniconda3\envs\mamitasHugo\lib\site-packages\wandb\integration\keras\keras.py", line 1004, in _save_model
    self.model.save(self.filepath, overwrite=True)
  File "C:\Users\Estudiantes\miniconda3\envs\mamitasHugo\lib\site-packages\keras\utils\traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "C:\Users\Estudiantes\miniconda3\envs\mamitasHugo\lib\site-packages\keras\saving\hdf5_format.py", line 80, in save_model_to_hdf5
    raise ImportError(
ImportError: `save_model()` using h5 format requires h5py. Could not import h5py.
2024-10-15 10:37:34,445 ERROR   Thread-1467 (_run_job):30356 [keras.py:_save_model():1012] `save_model()` using h5 format requires h5py. Could not import h5py.
Traceback (most recent call last):
  File "C:\Users\Estudiantes\miniconda3\envs\mamitasHugo\lib\site-packages\wandb\integration\keras\keras.py", line 1004, in _save_model
    self.model.save(self.filepath, overwrite=True)
  File "C:\Users\Estudiantes\miniconda3\envs\mamitasHugo\lib\site-packages\keras\utils\traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "C:\Users\Estudiantes\miniconda3\envs\mamitasHugo\lib\site-packages\keras\saving\hdf5_format.py", line 80, in save_model_to_hdf5
    raise ImportError(
ImportError: `save_model()` using h5 format requires h5py. Could not import h5py.
2024-10-15 10:37:59,295 ERROR   Thread-1467 (_run_job):30356 [keras.py:_save_model():1012] `save_model()` using h5 format requires h5py. Could not import h5py.
Traceback (most recent call last):
  File "C:\Users\Estudiantes\miniconda3\envs\mamitasHugo\lib\site-packages\wandb\integration\keras\keras.py", line 1004, in _save_model
    self.model.save(self.filepath, overwrite=True)
  File "C:\Users\Estudiantes\miniconda3\envs\mamitasHugo\lib\site-packages\keras\utils\traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "C:\Users\Estudiantes\miniconda3\envs\mamitasHugo\lib\site-packages\keras\saving\hdf5_format.py", line 80, in save_model_to_hdf5
    raise ImportError(
ImportError: `save_model()` using h5 format requires h5py. Could not import h5py.
2024-10-15 10:38:21,785 ERROR   Thread-1467 (_run_job):30356 [keras.py:_save_model():1012] `save_model()` using h5 format requires h5py. Could not import h5py.
Traceback (most recent call last):
  File "C:\Users\Estudiantes\miniconda3\envs\mamitasHugo\lib\site-packages\wandb\integration\keras\keras.py", line 1004, in _save_model
    self.model.save(self.filepath, overwrite=True)
  File "C:\Users\Estudiantes\miniconda3\envs\mamitasHugo\lib\site-packages\keras\utils\traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "C:\Users\Estudiantes\miniconda3\envs\mamitasHugo\lib\site-packages\keras\saving\hdf5_format.py", line 80, in save_model_to_hdf5
    raise ImportError(
ImportError: `save_model()` using h5 format requires h5py. Could not import h5py.
2024-10-15 10:38:46,331 ERROR   Thread-1467 (_run_job):30356 [keras.py:_save_model():1012] `save_model()` using h5 format requires h5py. Could not import h5py.
Traceback (most recent call last):
  File "C:\Users\Estudiantes\miniconda3\envs\mamitasHugo\lib\site-packages\wandb\integration\keras\keras.py", line 1004, in _save_model
    self.model.save(self.filepath, overwrite=True)
  File "C:\Users\Estudiantes\miniconda3\envs\mamitasHugo\lib\site-packages\keras\utils\traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "C:\Users\Estudiantes\miniconda3\envs\mamitasHugo\lib\site-packages\keras\saving\hdf5_format.py", line 80, in save_model_to_hdf5
    raise ImportError(
ImportError: `save_model()` using h5 format requires h5py. Could not import h5py.
2024-10-15 10:39:10,254 ERROR   Thread-1467 (_run_job):30356 [keras.py:_save_model():1012] `save_model()` using h5 format requires h5py. Could not import h5py.
Traceback (most recent call last):
  File "C:\Users\Estudiantes\miniconda3\envs\mamitasHugo\lib\site-packages\wandb\integration\keras\keras.py", line 1004, in _save_model
    self.model.save(self.filepath, overwrite=True)
  File "C:\Users\Estudiantes\miniconda3\envs\mamitasHugo\lib\site-packages\keras\utils\traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "C:\Users\Estudiantes\miniconda3\envs\mamitasHugo\lib\site-packages\keras\saving\hdf5_format.py", line 80, in save_model_to_hdf5
    raise ImportError(
ImportError: `save_model()` using h5 format requires h5py. Could not import h5py.
2024-10-15 10:39:42,846 ERROR   Thread-1467 (_run_job):30356 [keras.py:_save_model():1012] `save_model()` using h5 format requires h5py. Could not import h5py.
Traceback (most recent call last):
  File "C:\Users\Estudiantes\miniconda3\envs\mamitasHugo\lib\site-packages\wandb\integration\keras\keras.py", line 1004, in _save_model
    self.model.save(self.filepath, overwrite=True)
  File "C:\Users\Estudiantes\miniconda3\envs\mamitasHugo\lib\site-packages\keras\utils\traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "C:\Users\Estudiantes\miniconda3\envs\mamitasHugo\lib\site-packages\keras\saving\hdf5_format.py", line 80, in save_model_to_hdf5
    raise ImportError(
ImportError: `save_model()` using h5 format requires h5py. Could not import h5py.
2024-10-15 10:40:09,456 ERROR   Thread-1467 (_run_job):30356 [keras.py:_save_model():1012] `save_model()` using h5 format requires h5py. Could not import h5py.
Traceback (most recent call last):
  File "C:\Users\Estudiantes\miniconda3\envs\mamitasHugo\lib\site-packages\wandb\integration\keras\keras.py", line 1004, in _save_model
    self.model.save(self.filepath, overwrite=True)
  File "C:\Users\Estudiantes\miniconda3\envs\mamitasHugo\lib\site-packages\keras\utils\traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "C:\Users\Estudiantes\miniconda3\envs\mamitasHugo\lib\site-packages\keras\saving\hdf5_format.py", line 80, in save_model_to_hdf5
    raise ImportError(
ImportError: `save_model()` using h5 format requires h5py. Could not import h5py.
2024-10-15 10:40:33,806 ERROR   Thread-1467 (_run_job):30356 [keras.py:_save_model():1012] `save_model()` using h5 format requires h5py. Could not import h5py.
Traceback (most recent call last):
  File "C:\Users\Estudiantes\miniconda3\envs\mamitasHugo\lib\site-packages\wandb\integration\keras\keras.py", line 1004, in _save_model
    self.model.save(self.filepath, overwrite=True)
  File "C:\Users\Estudiantes\miniconda3\envs\mamitasHugo\lib\site-packages\keras\utils\traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "C:\Users\Estudiantes\miniconda3\envs\mamitasHugo\lib\site-packages\keras\saving\hdf5_format.py", line 80, in save_model_to_hdf5
    raise ImportError(
ImportError: `save_model()` using h5 format requires h5py. Could not import h5py.
2024-10-15 10:40:58,175 ERROR   Thread-1467 (_run_job):30356 [keras.py:_save_model():1012] `save_model()` using h5 format requires h5py. Could not import h5py.
Traceback (most recent call last):
  File "C:\Users\Estudiantes\miniconda3\envs\mamitasHugo\lib\site-packages\wandb\integration\keras\keras.py", line 1004, in _save_model
    self.model.save(self.filepath, overwrite=True)
  File "C:\Users\Estudiantes\miniconda3\envs\mamitasHugo\lib\site-packages\keras\utils\traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "C:\Users\Estudiantes\miniconda3\envs\mamitasHugo\lib\site-packages\keras\saving\hdf5_format.py", line 80, in save_model_to_hdf5
    raise ImportError(
ImportError: `save_model()` using h5 format requires h5py. Could not import h5py.
2024-10-15 10:41:22,547 ERROR   Thread-1467 (_run_job):30356 [keras.py:_save_model():1012] `save_model()` using h5 format requires h5py. Could not import h5py.
Traceback (most recent call last):
  File "C:\Users\Estudiantes\miniconda3\envs\mamitasHugo\lib\site-packages\wandb\integration\keras\keras.py", line 1004, in _save_model
    self.model.save(self.filepath, overwrite=True)
  File "C:\Users\Estudiantes\miniconda3\envs\mamitasHugo\lib\site-packages\keras\utils\traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "C:\Users\Estudiantes\miniconda3\envs\mamitasHugo\lib\site-packages\keras\saving\hdf5_format.py", line 80, in save_model_to_hdf5
    raise ImportError(
ImportError: `save_model()` using h5 format requires h5py. Could not import h5py.
2024-10-15 10:41:51,958 ERROR   Thread-1467 (_run_job):30356 [keras.py:_save_model():1012] `save_model()` using h5 format requires h5py. Could not import h5py.
Traceback (most recent call last):
  File "C:\Users\Estudiantes\miniconda3\envs\mamitasHugo\lib\site-packages\wandb\integration\keras\keras.py", line 1004, in _save_model
    self.model.save(self.filepath, overwrite=True)
  File "C:\Users\Estudiantes\miniconda3\envs\mamitasHugo\lib\site-packages\keras\utils\traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "C:\Users\Estudiantes\miniconda3\envs\mamitasHugo\lib\site-packages\keras\saving\hdf5_format.py", line 80, in save_model_to_hdf5
    raise ImportError(
ImportError: `save_model()` using h5 format requires h5py. Could not import h5py.
2024-10-15 10:42:22,092 ERROR   Thread-1467 (_run_job):30356 [keras.py:_save_model():1012] `save_model()` using h5 format requires h5py. Could not import h5py.
Traceback (most recent call last):
  File "C:\Users\Estudiantes\miniconda3\envs\mamitasHugo\lib\site-packages\wandb\integration\keras\keras.py", line 1004, in _save_model
    self.model.save(self.filepath, overwrite=True)
  File "C:\Users\Estudiantes\miniconda3\envs\mamitasHugo\lib\site-packages\keras\utils\traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "C:\Users\Estudiantes\miniconda3\envs\mamitasHugo\lib\site-packages\keras\saving\hdf5_format.py", line 80, in save_model_to_hdf5
    raise ImportError(
ImportError: `save_model()` using h5 format requires h5py. Could not import h5py.
2024-10-15 10:43:40,897 ERROR   Thread-1467 (_run_job):30356 [keras.py:_save_model():1012] `save_model()` using h5 format requires h5py. Could not import h5py.
Traceback (most recent call last):
  File "C:\Users\Estudiantes\miniconda3\envs\mamitasHugo\lib\site-packages\wandb\integration\keras\keras.py", line 1004, in _save_model
    self.model.save(self.filepath, overwrite=True)
  File "C:\Users\Estudiantes\miniconda3\envs\mamitasHugo\lib\site-packages\keras\utils\traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "C:\Users\Estudiantes\miniconda3\envs\mamitasHugo\lib\site-packages\keras\saving\hdf5_format.py", line 80, in save_model_to_hdf5
    raise ImportError(
ImportError: `save_model()` using h5 format requires h5py. Could not import h5py.
2024-10-15 10:44:26,992 ERROR   Thread-1467 (_run_job):30356 [keras.py:_save_model():1012] `save_model()` using h5 format requires h5py. Could not import h5py.
Traceback (most recent call last):
  File "C:\Users\Estudiantes\miniconda3\envs\mamitasHugo\lib\site-packages\wandb\integration\keras\keras.py", line 1004, in _save_model
    self.model.save(self.filepath, overwrite=True)
  File "C:\Users\Estudiantes\miniconda3\envs\mamitasHugo\lib\site-packages\keras\utils\traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "C:\Users\Estudiantes\miniconda3\envs\mamitasHugo\lib\site-packages\keras\saving\hdf5_format.py", line 80, in save_model_to_hdf5
    raise ImportError(
ImportError: `save_model()` using h5 format requires h5py. Could not import h5py.
2024-10-15 10:44:43,508 ERROR   Thread-1467 (_run_job):30356 [keras.py:_save_model():1012] `save_model()` using h5 format requires h5py. Could not import h5py.
Traceback (most recent call last):
  File "C:\Users\Estudiantes\miniconda3\envs\mamitasHugo\lib\site-packages\wandb\integration\keras\keras.py", line 1004, in _save_model
    self.model.save(self.filepath, overwrite=True)
  File "C:\Users\Estudiantes\miniconda3\envs\mamitasHugo\lib\site-packages\keras\utils\traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "C:\Users\Estudiantes\miniconda3\envs\mamitasHugo\lib\site-packages\keras\saving\hdf5_format.py", line 80, in save_model_to_hdf5
    raise ImportError(
ImportError: `save_model()` using h5 format requires h5py. Could not import h5py.
2024-10-15 10:45:00,204 ERROR   Thread-1467 (_run_job):30356 [keras.py:_save_model():1012] `save_model()` using h5 format requires h5py. Could not import h5py.
Traceback (most recent call last):
  File "C:\Users\Estudiantes\miniconda3\envs\mamitasHugo\lib\site-packages\wandb\integration\keras\keras.py", line 1004, in _save_model
    self.model.save(self.filepath, overwrite=True)
  File "C:\Users\Estudiantes\miniconda3\envs\mamitasHugo\lib\site-packages\keras\utils\traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "C:\Users\Estudiantes\miniconda3\envs\mamitasHugo\lib\site-packages\keras\saving\hdf5_format.py", line 80, in save_model_to_hdf5
    raise ImportError(
ImportError: `save_model()` using h5 format requires h5py. Could not import h5py.
2024-10-15 10:45:13,797 ERROR   Thread-1467 (_run_job):30356 [keras.py:_save_model():1012] `save_model()` using h5 format requires h5py. Could not import h5py.
Traceback (most recent call last):
  File "C:\Users\Estudiantes\miniconda3\envs\mamitasHugo\lib\site-packages\wandb\integration\keras\keras.py", line 1004, in _save_model
    self.model.save(self.filepath, overwrite=True)
  File "C:\Users\Estudiantes\miniconda3\envs\mamitasHugo\lib\site-packages\keras\utils\traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "C:\Users\Estudiantes\miniconda3\envs\mamitasHugo\lib\site-packages\keras\saving\hdf5_format.py", line 80, in save_model_to_hdf5
    raise ImportError(
ImportError: `save_model()` using h5 format requires h5py. Could not import h5py.
2024-10-15 10:45:34,802 INFO    Thread-1467 (_run_job):30356 [wandb_run.py:_finish():1962] finishing run mamitas/weak_supervised_learning/vzg97yv3
2024-10-15 10:45:34,802 INFO    Thread-1467 (_run_job):30356 [wandb_run.py:_atexit_cleanup():2202] got exitcode: 0
2024-10-15 10:45:34,802 INFO    Thread-1467 (_run_job):30356 [wandb_run.py:_restore():2185] restore
2024-10-15 10:45:34,802 INFO    Thread-1467 (_run_job):30356 [wandb_run.py:_restore():2191] restore done
2024-10-15 10:45:42,163 INFO    Thread-1467 (_run_job):30356 [wandb_run.py:_footer_history_summary_info():3760] rendering history
2024-10-15 10:45:42,163 INFO    Thread-1467 (_run_job):30356 [wandb_run.py:_footer_history_summary_info():3792] rendering summary
2024-10-15 10:45:42,163 INFO    Thread-1467 (_run_job):30356 [wandb_run.py:_footer_sync_info():3719] logging synced files
