2024-09-24 10:46:56,687 INFO    Thread-10 (_run_job):19316 [wandb_setup.py:_flush():76] Current SDK version is 0.16.0
2024-09-24 10:46:56,687 INFO    Thread-10 (_run_job):19316 [wandb_setup.py:_flush():76] Configure stats pid to 19316
2024-09-24 10:46:56,687 INFO    Thread-10 (_run_job):19316 [wandb_setup.py:_flush():76] Loading settings from C:\Users\Estudiantes\.config\wandb\settings
2024-09-24 10:46:56,687 INFO    Thread-10 (_run_job):19316 [wandb_setup.py:_flush():76] Loading settings from C:\Users\Estudiantes\Documents\copy\Mamitas-Unal\wandb\settings
2024-09-24 10:46:56,687 INFO    Thread-10 (_run_job):19316 [wandb_setup.py:_flush():76] Loading settings from environment variables: {'project': 'weak_supervised_learning', 'entity': 'mamitas', 'api_key': '***REDACTED***', 'root_dir': 'C:\\Users\\Estudiantes\\Documents\\copy\\Mamitas-Unal', 'sweep_id': 'w0nuti5u', 'run_id': 'zac958z0', 'sweep_param_path': 'C:\\Users\\Estudiantes\\Documents\\copy\\Mamitas-Unal\\wandb\\sweep-w0nuti5u\\config-zac958z0.yaml'}
2024-09-24 10:46:56,687 INFO    Thread-10 (_run_job):19316 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2024-09-24 10:46:56,687 INFO    Thread-10 (_run_job):19316 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program_relpath': 'code\\trains.py', 'program_abspath': 'c:\\Users\\Estudiantes\\Documents\\copy\\Mamitas-Unal\\code\\trains.py', 'program': 'c:\\Users\\Estudiantes\\Documents\\copy\\Mamitas-Unal\\code\\trains.py'}
2024-09-24 10:46:56,687 INFO    Thread-10 (_run_job):19316 [wandb_init.py:_log_setup():524] Logging user logs to C:\Users\Estudiantes\Documents\copy\Mamitas-Unal\wandb\run-20240924_104656-zac958z0\logs\debug.log
2024-09-24 10:46:56,687 INFO    Thread-10 (_run_job):19316 [wandb_init.py:_log_setup():525] Logging internal logs to C:\Users\Estudiantes\Documents\copy\Mamitas-Unal\wandb\run-20240924_104656-zac958z0\logs\debug-internal.log
2024-09-24 10:46:56,687 INFO    Thread-10 (_run_job):19316 [wandb_init.py:init():564] calling init triggers
2024-09-24 10:46:56,687 INFO    Thread-10 (_run_job):19316 [wandb_init.py:init():571] wandb.init called with sweep_config: {'dataset': 'infrared_thermal_feet', 'model': 'f_b'}
config: {}
2024-09-24 10:46:56,687 INFO    Thread-10 (_run_job):19316 [wandb_init.py:init():614] starting backend
2024-09-24 10:46:56,687 INFO    Thread-10 (_run_job):19316 [wandb_init.py:init():618] setting up manager
2024-09-24 10:46:56,697 INFO    Thread-10 (_run_job):19316 [backend.py:_multiprocessing_setup():105] multiprocessing start_methods=spawn, using: spawn
2024-09-24 10:46:56,704 INFO    Thread-10 (_run_job):19316 [wandb_init.py:init():624] backend started and connected
2024-09-24 10:46:56,710 INFO    Thread-10 (_run_job):19316 [wandb_run.py:_config_callback():1342] config_cb None None {'dataset': 'infrared_thermal_feet', 'model': 'f_b'}
2024-09-24 10:46:56,710 INFO    Thread-10 (_run_job):19316 [wandb_init.py:init():716] updated telemetry
2024-09-24 10:46:56,738 INFO    Thread-10 (_run_job):19316 [wandb_init.py:init():749] communicating run to backend with 90.0 second timeout
2024-09-24 10:46:58,434 INFO    Thread-10 (_run_job):19316 [wandb_run.py:_on_init():2254] communicating current version
2024-09-24 10:46:58,520 INFO    Thread-10 (_run_job):19316 [wandb_run.py:_on_init():2263] got version response upgrade_message: "wandb version 0.18.1 is available!  To upgrade, please run:\n $ pip install wandb --upgrade"

2024-09-24 10:46:58,520 INFO    Thread-10 (_run_job):19316 [wandb_init.py:init():800] starting run threads in backend
2024-09-24 10:47:00,782 INFO    Thread-10 (_run_job):19316 [wandb_run.py:_console_start():2233] atexit reg
2024-09-24 10:47:00,782 INFO    Thread-10 (_run_job):19316 [wandb_run.py:_redirect():2088] redirect: wrap_raw
2024-09-24 10:47:00,782 INFO    Thread-10 (_run_job):19316 [wandb_run.py:_redirect():2153] Wrapping output streams.
2024-09-24 10:47:00,782 INFO    Thread-10 (_run_job):19316 [wandb_run.py:_redirect():2178] Redirects installed.
2024-09-24 10:47:00,783 INFO    Thread-10 (_run_job):19316 [wandb_init.py:init():841] run started, returning control to user process
2024-09-24 10:47:39,962 ERROR   Thread-10 (_run_job):19316 [keras.py:_save_model():1012] `save_model()` using h5 format requires h5py. Could not import h5py.
Traceback (most recent call last):
  File "C:\Users\Estudiantes\miniconda3\envs\mamitasHugo\lib\site-packages\wandb\integration\keras\keras.py", line 1004, in _save_model
    self.model.save(self.filepath, overwrite=True)
  File "C:\Users\Estudiantes\miniconda3\envs\mamitasHugo\lib\site-packages\keras\src\utils\traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "C:\Users\Estudiantes\miniconda3\envs\mamitasHugo\lib\site-packages\keras\src\saving\legacy\hdf5_format.py", line 79, in save_model_to_hdf5
    raise ImportError(
ImportError: `save_model()` using h5 format requires h5py. Could not import h5py.
2024-09-24 10:48:14,322 ERROR   Thread-10 (_run_job):19316 [keras.py:_save_model():1012] `save_model()` using h5 format requires h5py. Could not import h5py.
Traceback (most recent call last):
  File "C:\Users\Estudiantes\miniconda3\envs\mamitasHugo\lib\site-packages\wandb\integration\keras\keras.py", line 1004, in _save_model
    self.model.save(self.filepath, overwrite=True)
  File "C:\Users\Estudiantes\miniconda3\envs\mamitasHugo\lib\site-packages\keras\src\utils\traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "C:\Users\Estudiantes\miniconda3\envs\mamitasHugo\lib\site-packages\keras\src\saving\legacy\hdf5_format.py", line 79, in save_model_to_hdf5
    raise ImportError(
ImportError: `save_model()` using h5 format requires h5py. Could not import h5py.
2024-09-24 10:48:48,841 ERROR   Thread-10 (_run_job):19316 [keras.py:_save_model():1012] `save_model()` using h5 format requires h5py. Could not import h5py.
Traceback (most recent call last):
  File "C:\Users\Estudiantes\miniconda3\envs\mamitasHugo\lib\site-packages\wandb\integration\keras\keras.py", line 1004, in _save_model
    self.model.save(self.filepath, overwrite=True)
  File "C:\Users\Estudiantes\miniconda3\envs\mamitasHugo\lib\site-packages\keras\src\utils\traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "C:\Users\Estudiantes\miniconda3\envs\mamitasHugo\lib\site-packages\keras\src\saving\legacy\hdf5_format.py", line 79, in save_model_to_hdf5
    raise ImportError(
ImportError: `save_model()` using h5 format requires h5py. Could not import h5py.
2024-09-24 10:49:24,056 ERROR   Thread-10 (_run_job):19316 [keras.py:_save_model():1012] `save_model()` using h5 format requires h5py. Could not import h5py.
Traceback (most recent call last):
  File "C:\Users\Estudiantes\miniconda3\envs\mamitasHugo\lib\site-packages\wandb\integration\keras\keras.py", line 1004, in _save_model
    self.model.save(self.filepath, overwrite=True)
  File "C:\Users\Estudiantes\miniconda3\envs\mamitasHugo\lib\site-packages\keras\src\utils\traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "C:\Users\Estudiantes\miniconda3\envs\mamitasHugo\lib\site-packages\keras\src\saving\legacy\hdf5_format.py", line 79, in save_model_to_hdf5
    raise ImportError(
ImportError: `save_model()` using h5 format requires h5py. Could not import h5py.
2024-09-24 10:50:01,060 ERROR   Thread-10 (_run_job):19316 [keras.py:_save_model():1012] `save_model()` using h5 format requires h5py. Could not import h5py.
Traceback (most recent call last):
  File "C:\Users\Estudiantes\miniconda3\envs\mamitasHugo\lib\site-packages\wandb\integration\keras\keras.py", line 1004, in _save_model
    self.model.save(self.filepath, overwrite=True)
  File "C:\Users\Estudiantes\miniconda3\envs\mamitasHugo\lib\site-packages\keras\src\utils\traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "C:\Users\Estudiantes\miniconda3\envs\mamitasHugo\lib\site-packages\keras\src\saving\legacy\hdf5_format.py", line 79, in save_model_to_hdf5
    raise ImportError(
ImportError: `save_model()` using h5 format requires h5py. Could not import h5py.
